### ISSUE TITLE
Action Undo

### ISSUE THREAD

**Issue by GABowers** [VespucciProject/Vespucci#3]
Implement undo method which uses macro system to re-import original spectra and re-perform all actions up to the "undo point." Implement dialog or display which shows and allows the user to select a particular action to undo back to.

**Comment by dpfoose** [comment]
This is a good idea @GABowers. We discussed implementation earlier. When you're done with the AHCA implementation please work on this.

**Comment by dpfoose** [comment]
With the current macro system, which both holds history and can send history from the history viewer to the macro editor, it is now trivial for the user to do this themselves manually. This may be preferred. I feel like re-importing the file import could create some issues, and this level of undo is not found in any of the comparable packages. It would make more sense for the user to manually re-import the dataset then run the macro containing what (s)he wants to do.

With @GABowers moving away from work on Vespucci and toward more interesting research, I don't see this getting done. Will close the issue.
